### ISSUE TITLE
Provide CI to test minishift add-ons

### ISSUE THREAD

**Issue by fabiand** [minishift/minishift-addons#27]
The minishift team could provide infrastructure to run CI against all provided add-ons.

The responsibilities would be
- minishift team to provide the infra
- addon owners to provide the tests

**Comment by gbraad** [comment]
the problem is nested virtualization is mostly not available on public CI. Also, the time to run this would likely be very long. For each addon we would need to recreate the instance.

**Comment by fabiand** [comment]
We - KubeVirt - might also rely on minishift for demo purpose. Eventually we can run some CI on our infra (which supports nesting and parallel jobs), we are currently already working on a nice github integration, because we need it for ourselfs. But I need to check this.

**Comment by gbraad** [comment]
I just joined #kubevirt and let's see if we can discuss this further.

**Comment by hferentschik** [comment]
There is not only the problem of virtualisation, but as @gbraad says the time it takes to run such tests. And what would be test? Just that the add-on applies? This is for sure one step of verification, but it does not mean that the add-on does what it should. Often the outcome of an add-on apply is not even directly verifiable, since it might kick off some sort of provisioning job. If you want to verify that an add-on actually functions, what type of txt harness do you use (to assert certain conditions)? Would we enforce a framework?

IMO there are too many unknowns here. It's a nice goal and I for sure it would be a nice to have, but I feel the commitment needed by the Minishift team would be too high. At least for now.

A simple step which can be taken though, is to verify that the add-ons comply to the Minishift add-on DSl in terms of required metadata as well as the commands used. For this no virtualisation is needed, but one can write a simple unit test which iterates the add-ons and for each add-on instantiates the add-on parser and asserts that the outcome is a valid add-on instance. Obviously this is just a very basic verification, but I'd start there.

**Comment by fabiand** [comment]
+1 on verifying the metadata.

And yes, I don't think that the tests for the add-ons should be provided by the minishift team.

But the add-on authors should be able to provide some snippet which will ensure basic functionality.
I was thinking along the lines of allowing authors to provide a small file, which does some sanity checks against their deployed add-on, to enusre it's working correctly.
If this file is not present, then it will not be tested.

The minishift team can however can make sure to run theses test regularly on an infra which supports it.

**Comment by gbraad** [comment]
We have implemented a way to allow features to test addons. However, we still do not really have a shared CI environment... so for the moment we have a small subset of addons we can/will test.

**Comment by fabiand** [comment]
That's awesome (emojis were not enough).
